### ISSUE TITLE
Can't see the title properly.

### ISSUE THREAD

**Issue by lakshani** [wso2/docs-apim#4267] opened 2021-06-23 09:21 UTC
![image](https://user-images.githubusercontent.com/11018512/123071579-69001b00-d432-11eb-9140-4b2c8ce32c4e.png)

**Comment by Mariangela** [comment] 2021-06-23 12:39
@lakshani , thank you for reporting this issue. Can you please provide more details in this regard so that we can get a better understanding on it.  Because I do not see this issue at my end.

<img width="1680" alt="Screenshot 2021-06-23 at 18 06 13" src="https://user-images.githubusercontent.com/5195851/123097839-22b8b500-d44e-11eb-903d-5c7df18cf1f1.png">

**Comment by Mariangela** [comment] 2021-06-23 12:44
I managed to reproduce this. It appears when the screen with is smaller than 1306px.

<img width="1308" alt="Screenshot 2021-06-23 at 18 12 57" src="https://user-images.githubusercontent.com/5195851/123098490-d28e2280-d44e-11eb-9b40-fb876a605a1f.png">

**Comment by Mariangela** [comment] 2021-06-23 12:45
@erangatl , can you please look into this UX issue.

**Comment by Mariangela** [comment] 2021-06-23 13:13
@erangatl as discussed offline, please look into this issue.

**Comment by Mariangela** [comment] 2021-07-08 06:05
This needs to be fixed in 3.x and 4.0.0

**Comment by Mariangela** [comment] 2021-07-08 06:09
This is not applicable to 3.x and it has been fixed in 4.0.0

**Closed by Mariangela** 2021-07-08 06:09 UTC
Labels: API-M-4.0.0, Type/UX, help wanted
