### ISSUE TITLE
Change the directory paths that needs to be sync between nodes

### ISSUE THREAD

**Issue by NipuniC** [wso2/docs-apim#2247] opened 2020-11-16 12:36 UTC
**Description:**

Only **synapse-configs** and **executionplans** folders needs to be shared across the nodes. The doc [1] and [2] needs to be corrected.

[1] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster/
[2] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts/#common-runtime-and-configuration-artifacts

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM-3.x.x

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment] 2020-11-17 12:53
duplicate of https://github.com/wso2/docs-apim/issues/1594

**Closed by shaniR** 2020-11-17 12:53 UTC
