### ISSUE TITLE
ForgeRock key manager documentation is outdated

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/docs-apim#3604] opened 2021-04-16 05:55 UTC
**Description:**

The ForgeRock key manager documentation[1] steps seems to be outdated from their newer versions. Furthermore, there's an instance where APIM 3.2.0 is mentioned instead of 4.0.0.

![image](https://user-images.githubusercontent.com/25485783/114978148-7636e180-9ea6-11eb-9ed2-c4013b1406f1.png)

[1] https://apim.docs.wso2.com/en/4.0.0-dev/administer/key-managers/configure-forgerock-connector/

**Comment by samgnaniah** [comment] 2021-09-01 12:40
Closing this as this is a duplicate of https://github.com/wso2/docs-apim/issues/3473

**Closed by samgnaniah** 2021-09-01 12:40 UTC
Labels: help wanted, Type/Bug, API-M-4.0.0
