### ISSUE TITLE
[URGENT] Doc Feedback: All the links pointed to REST API Specs are broken

### ISSUE THREAD

**Issue by pandulakb** [wso2/docs-apim#6210] opened 2022-09-08 11:29 UTC
Location : https://apim.docs.wso2.com/en/latest/reference/product-apis/overview/
Location : https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/overview/

All the links pointed to REST API Specs are broken.
Please fix this with highest priority, as customer is waiting for these specs.

**Comment by ruthryi** [comment] 2022-09-09 04:41
Closing this, since it was not reproduced. Both pages/links are working.

Thanks,
Ruthryi

**Closed by ruthryi** 2022-09-09 04:41 UTC
Labels: Type/Bug, Severity/Blocker, Priority/Highest, Affected/APIM-4.0.0
