### ISSUE TITLE
Add documentation for revers proxy auto mode

### ISSUE THREAD

**Issue by tmkasun** [wso2/docs-apim#1540] opened 2020-07-15 15:45 UTC
**Description:**

We want to document `How to change callback origin dynamically` . I think we can include this information [here](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer/#step-3-configure-the-reverse-proxy-settings-in-the-product), Because in old [2.6.0 documentation](https://docs.wso2.com/display/AM260/Configuring+the+Proxy+Server+and+the+Load+Balancer), we have mentioned about the reverse proxy `auto` mode under the same topic.

[This is](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/conf/settings.js#L10) the new configuration file for reverse proxy config, This file comes in the following location in the pack
```
<APIM_ROOT>/repository/deployment/server/jaggeryapps/publisher/site/public/conf/settings.js
```

**Note** : New config does not have `auto` as a config value for `customUrl.enable` property

```javascript
customUrl: { // Dynamically set the redirect origin according to the forwardedHeader host|proxyPort combination
            enabled: false,
            forwardedHeader: 'X-Forwarded-For',
        },
```

Instead, if you enable the `customUrl` and we see a `forwardedHeader` head in the request, We automatically use it for constructing the callback URL for OIDC code flow.

**Suggested Labels:**
- N/A

**Suggested Assignees:**
- @shaniR 

**Affected Product Version:**

- APIM 3.0.0 (WUM)
- APIM 3.1.0
- APIM 3.2.0

**OS, DB, other environment details and versions:**    
- Mac OS
- H2 (Default)
- Chrome 85

**Steps to reproduce:**
- Create 2 hostname mappings to same API Manager server (You can use `/etc/hosts`)
- Change the API Manager server hostname to one of the above hostnames
- Try to login to API Manager Publisher (or any other) portal using the hostname that was not given as the server hostname
- You will get an error unless you do the above-suggested doc steps

**Related Issues:**
- N/A

**Comment by uvindra** [comment] 2020-12-23 10:52
The issue is already addressed in 3.2.0 and master

**Closed by uvindra** 2020-12-23 10:52 UTC
Labels: API-M-3.0.0, API-M-3.1.0, API-M-3.2.0, Priority/Normal, Resolution/Fixed, Type/Improvement, component/install-and-setup-setup
