### ISSUE TITLE
Doc Feedback: Configuring Analytics with APIM 4.0.0 not working

### ISSUE THREAD

**Issue by waqasalirazzaq** [wso2/docs-apim#4119] opened 2021-05-28 19:33 UTC
Location : https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/configure-analytics/configure-synapse-gateway/
By following the step apim gives below error
`TID: [-1] [] [2021-05-28 18:48:45,118] ERROR {org.wso2.am.analytics.publisher.client.EventHubClient} - Recoverable error occurred when creating Eventhub Client. Retry attempts will be made in 15 sec. Reason :Provided authentication endpoint https://analytics-event-auth.choreo.dev/auth/v1 is not reachable.`

Although endpoint is reachable via curl from server.

**Comment by Mariangela** [comment] 2021-06-14 10:31
@jaadds , please assign someone to investigate into this Git issue.

**Comment by fazlan-nazeem** [comment] 2021-07-27 12:20
We were only able to reproduce this issue when the gateway did not have access to the internet. Please check whether the gateway is configured to use a proxy server in your environment and whether the proxy server allows this URL. 

Since this isn't an issue in the product, we are closing this issue.

**Closed by fazlan-nazeem** 2021-07-27 12:20 UTC
Labels: API-M-4.0.0, Type/Bug, help wanted
