### ISSUE TITLE
Issues in GraphQL docs

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#3187] opened 2021-02-17 16:36 UTC
**Description:**

_Issue 1_
I was trying to do the steps to start a GraphQL backend service as mention in [1] and [2] as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/25246848/108233993-59ae4f80-716a-11eb-8477-d74fa50b66fd.png)

After following the above steps I was unable to start the server and got the below error.

![image](https://user-images.githubusercontent.com/25246848/108234132-8498a380-716a-11eb-9263-1b10caf95240.png)

I tried with different node versions (12.x and 14.x), but didn't work. 

**We need to specify the correct node/npm versions to start this server or change the example with a working server that can be used irrespective of the node/npm version. This change should be done in [1] and [2] both**

_Issue 2_
The last screenshot of [1] and [3] is shown below.

![image](https://user-images.githubusercontent.com/25246848/108234800-2a4c1280-716b-11eb-8059-2438277456cb.png)

But when I click on it, it redirects to another screenshot as shown below which is wrong.

![image](https://user-images.githubusercontent.com/25246848/108234956-58c9ed80-716b-11eb-8efd-9b6a2ae465ad.png)

This redirection needs to be fixed.

[1] https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-a-graphql-api/#create-and-publish-a-graphql-api
[2] https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/create-a-graphql-api/
[3] https://apim.docs.wso2.com/en/latest/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console/#invoke-a-graphql-api-using-the-integrated-graphql-console

**Affected Product Version:**
API-M 4.0.0
API-M 3.2.0
API-M 3.1.0
API-M 3.0.0

**OS, DB, other environment details and versions:**    
OS: Ubuntu 20.04.1 LTS
node version: v12.18.2

**Comment by Mariangela** [comment] 2021-02-18 06:55
Fixed the 2nd part of the issue with the above 2 PRs in 3.2.0. This is not applicable to 4.0.0 as the issue is not present.

**Comment by RakhithaRR** [comment] 2021-02-18 07:04
Issue 1 mentioned in the description was caused by a missing file in the GraphQL sample project. This has been fixed with https://github.com/wso2/samples-apim/pull/19.

**Closed** 2021-02-18 07:06 UTC
Labels: API-M-3.0.0, API-M-3.1.0, API-M-3.2.0, API-M-4.0.0, Priority/High, Resolution/Fixed, Severity/Critical, component/learn-design-apis, help wanted
