### ISSUE TITLE
Need to update Application Sharing page instructions

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/docs-apim#6489] opened 2022-12-04 06:48 UTC
**Description:**
Need to fix the documentation according to https://github.com/wso2/api-manager/issues/1071

**Comment by SavinduDimal** [comment] 2023-03-02 12:03
Tested Application Sharing in `wso2am-4.2.0-beta` pack according to the instructions given in [1]. However the issue mentioned at [2] did not reproduce and Application sharing is working as intended. Therefore closing this issue.

[1] - https://apim.docs.wso2.com/en/4.2.0/consume/manage-application/sharing-applications/sharing-applications/
[2] - https://github.com/wso2/api-manager/issues/1071#issue-1471200571

**Closed by SavinduDimal** 2023-03-02 12:03 UTC
Labels: API-M 4.2.0
