### ISSUE TITLE
Wrong instructions to create a topic and start consumer

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/docs-apim#3406] opened 2021-03-29 02:00 UTC
**Description:**
Please refer to https://github.com/wso2/micro-integrator/issues/2158

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment] 2021-09-01 11:59
This is a duplicate of https://github.com/wso2/docs-apim/issues/3649

**Closed by samgnaniah** 2021-09-01 11:59 UTC
Labels: Type/Bug, Type/Docs, API-M-4.0.0, component/micro-integrator
