### ISSUE TITLE
APIM 3.0 Documentation search not working

### ISSUE THREAD

**Issue by Christopher-Davey** [wso2/docs-apim#1053] opened 2020-04-17 10:47 UTC
**Description:**
APIM 3.0 Documentation search not working, no results from even a search for API.

**Affected Product Version:**
https://apim.docs.wso2.com/en/3.0.0/

**Comment by Mariangela** [comment] 2020-04-17 11:24
@tmkasun , can you please look into the root cause of this issue.

**Comment by tmkasun** [comment] 2020-04-17 11:30
Yes, We have analyzed this issue and found that changing the sitemap.xml has caused this issue
Hi @shaniR , As discussed offline , shall we create a consolidated sitemap file for the entire doc site 

As a temporary fix , We can change the site URL in mkdocs config for 3.0.0

**Comment by tmkasun** [comment] 2020-04-17 11:37
Sent a PR to Algolia repo https://github.com/algolia/docsearch-configs/pull/1867

Search will be back once this PR gets merged and indexed ( in the worst case will take 24 hours from the time the PR gets merged ) the 3.0.0 doc content

**Comment by Mariangela** [comment] 2020-04-21 05:58
The search issue in 3.0.0 is temporarily fixed by updating the sitemap file in algolia configs. However, the permanent fix is to implement the consolidated sitemap change. Therefore, we will be keeping this Git issue open until that task is completed.

**Comment by shaniR** [comment] 2020-11-13 17:07
tracked by https://github.com/wso2/docs-apim/issues/838

**Closed by shaniR** 2020-11-13 17:07 UTC
Labels: API-M-3.0.0, help wanted
